/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://eap7flbivreyjjichwrqkmhope.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gc2jifokgjgrpeoj5bxtji46fi",
    "aws_cloud_logic_custom": [
        {
            "name": "igvdata",
            "endpoint": "https://xoy6stxwff.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:3a3ea2b4-bf86-404e-adfa-1ef78c0b93c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HB7WL1qDJ",
    "aws_user_pools_web_client_id": "2q8788visrrlqc9efo1f939vog",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "igovoteapp-storage-9f97588c204849-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
